enum IncidentTypes {
	CREATE_INCIDENT_START = "CREATE_INCIDENT_START",
	CREATE_INCIDENT_SUCCESS = "CREATE_INCIDENT_SUCCESS",
	FETCH_USER_INCIDENTS_START = "FETCH_USER_INCIDENTS_START",
	FETCH_USER_INCIDENTS_SUCCESS = "FETCH_USER_INCIDENTS_SUCCESS",
	RESET_INCIDENT_DATE = "RESET_INCIDENT_DATE",
	POST_COMMENT = "POST_COMMENT",
	DELETE_COMMENT = "DELETE_COMMENT",
	UPDATE_COMMENT = "UPDATE_COMMENT",
	DELETE_INCIDENT_START = "DELETE_INCIDENT_START",
	DELETE_INCIDENT_SUCCESS = "DELETE_INCIDENT_SUCCESS",
	INCIDENT_ERROR = "INCIDENT_ERROR",
}

export default IncidentTypes;
